FROM rust:1.54.0
WORKDIR /usr/src/wabper
COPY ./Cargo.toml ./Cargo.toml
COPY ./docker/entrypoint.sh /entrypoint.sh
COPY ./packages ./packages
COPY ./server ./server
RUN cargo install cargo-watch
EXPOSE 8080
ENTRYPOINT [ "/entrypoint.sh" ]